name: job-setup
description: 'Prepare jobs environment'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Reuse action
      uses: ./.github/actions/build

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Or your project's Python version

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
