name: odoo-integration
on: workflow_call
jobs:
  odoo-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: artg-module
      - name: Checkout Odoo 18
        uses: actions/checkout@v4
        with:
          repository: odoo/odoo
          fetch-depth: 0
          path: odoo-18