name: odoo-integration
on: workflow_call
jobs:
  odoo-integration:
    runs-on: ubuntu-latest
    permissions:
      packages: write # for other steps in this workflow
    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          path: artg-module
#          ref: ${{ github.ref_name }}
#      - name: Checkout Odoo 18
#        uses: actions/checkout@v4
#        with:
#          repository: odoo/odoo
#          ref: '18.0'
#          fetch-depth: 0
#          # /home/runner/work/artgicicd/artgicicd/odoo-18
#          path: odoo-18
      - name: Checkout Odoo 18 Enterprise
        uses: actions/checkout@v4
        with:
          repository: odoo/enterprise
          ref: '18.0'
          fetch-depth: 0
#          token:  ${{secrets.ARTGI_CICD_PAT}}
          # /home/runner/work/artgicicd/artgicicd/odoo-enterprise-18
          path: odoo-enterprise-18
