name: pre-commit
on:
  push:
    branches: [ '*' ]
jobs:
  push:
    uses: ./.github/workflows/pre-commit-workflow-template.yml
  odoo-integration:
    needs: [push]
    uses: ./.github/workflows/odoo-integration-workflow.yml