on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]
    types: [opened, reopened]
jobs:
  push:
    if: github.event_name == 'push' && ${{ !startsWith(github.ref, 'refs/pull/') }}
    uses: ./.github/workflows/pre-commit-workflow-template.yml

  pull-request:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/pre-commit-workflow-template.yml
#  odoo-integration:
#    needs: [push]
#    uses: ./.github/workflows/odoo-integration-workflow.yml

  odoo-integration:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - name: Checkout Odoo 18 Enterprise
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ARTGI_FINE_TOKEN }}
          repository: PGarces-arthomson/enterprise
          ref: '18.0'
          fetch-depth: 0
          # /home/runner/work/artgicicd/artgicicd/odoo-18
          path: odoo-enterprise-18
          
