on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]
    types: [opened, reopened]
jobs:
  push:
    if: github.event_name == 'push' && ${{ !startsWith(github.ref, 'refs/pull/') }}
    uses: ./.github/workflows/pre-commit-workflow-template.yml

  pull-request:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/pre-commit-workflow-template.yml

  Prepare-odoo-environment:
    runs-on: ubuntu-latest
    needs: [push]
    steps:

      - name: Checkout ARTGI Repository
        uses: actions/checkout@v4
        with:
          path: artg-modules
          fetch-depth: 2
          ref: ${{ github.ref_name }}

#      - name: Checkout Odoo 18
#        uses: actions/checkout@v4
#        with:
#          repository: odoo/odoo
#          ref: '18.0'
#          fetch-depth: 0
#          # /home/runner/work/artgicicd/artgicicd/odoo-18
#          path: odoo-18

#      - name: Checkout Odoo Enterprise 18
#        uses: actions/checkout@v4
#        with:
#          repository: PGarces-arthomson/enterprise
#          ref: '18.0'
#          # Active Repo PAT
#          token: ${{ secrets.ARTGI_CICD_PAT }}
#
#          # /home/runner/work/artgicicd/artgicicd/odoo-enterprise-18
#          path: odoo-enterprise-18

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'

#      - name: Install dependencies
#        run: |
#          cd artg-modules && pwd
#          ls
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#          pip install -r artgicicd/odoo-18/requirements.txt
          
#      - name: Install development libraries and dependencies
#        run: |
#          sudo apt-get install -y python3-dev libxml2-dev libxslt1-dev zlib1g-dev libsasl2-dev libldap2-dev build-essential libssl-dev libffi-dev libmysqlclient-dev libjpeg-dev libpq-dev libjpeg8-dev liblcms2-dev libblas-dev libatlas-base-dev
#
#      - name: Install Node Js and NPM
#        run: |
#          sudo apt-get install -y npm
#          sudo npm install -g less less-plugin-clean-css
#          sudo apt-get install -y node-less

      - name: Setup Postgres
        run: |
          sudo apt-get install -y postgresql
          sudo service postgresql start
          sudo su - postgres
          psql
          CREATE USER runner WITH CREATEDB SUPERUSER PASSWORD 'runner'
          
          \q
          exit

      - name: Create Odoo configuration
        run: |
          echo "[options]" > ~/odoo.conf
          echo "db_host = postgres" >> ~/odoo.conf
          echo "db_port = 5432" >> ~/odoo.conf
          echo "db_user = odoo18" >> ~/odoo.conf
          echo "db_password = runner" >> ~/odoo.conf
          echo "test_enable = True" >> ~/odoo.conf
          cd ~ && pwd
          cat odoo.conf

